# Generated by Django 4.1.7 on 2023-03-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=30)),
                ('mensaje', models.CharField(max_length=1000)),
            ],
        ),
    ]
