# Generated by Django 4.1.7 on 2023-03-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('informacion', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
