# Generated by Django 4.1.7 on 2023-03-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_publicidad_alter_artista_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
