# Generated by Django 4.1.7 on 2023-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_programa_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
