# Generated by Django 4.1.7 on 2023-03-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_programa_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
