# Generated by Django 4.1.7 on 2023-03-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_publicidad_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
