# Generated by Django 4.1.7 on 2023-03-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_subprograma_delete_radio_remove_programa_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='subPrograma',
        ),
        migrations.AddField(
            model_name='subprograma',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.programa'),
        ),
    ]
