# Generated by Django 4.1.7 on 2023-03-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_programa_codigo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubPrograma',
            new_name='Programacion',
        ),
    ]
