# Generated by Django 4.1.7 on 2023-10-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_contacto_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosHilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('url', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='programacion',
            options={'ordering': ['-fecha', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='publicidad',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='programacion',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publicidad',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
