# Generated by Django 4.1.7 on 2023-10-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_song_alter_programacion_options_programacion_ano_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
