# Generated by Django 4.1.7 on 2023-10-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_usuarioshilos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuariosHilos',
            new_name='UsuariosHilo',
        ),
    ]
