# Generated by Django 4.1.7 on 2023-10-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_usuarioshilos_usuarioshilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioshilo',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
