# Generated by Django 4.1.7 on 2023-10-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_usuarioshilo_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='publicidad',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='programacion',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
