# Generated by Django 4.1.7 on 2023-03-16 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_radio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Transmision')),
                ('codigoProgramas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['fecha', 'nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Radio',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='codigoRadio',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='fecha',
        ),
        migrations.AddField(
            model_name='programa',
            name='certificadoLoc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='conductor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='subPrograma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subprograma'),
        ),
    ]
