# Generated by Django 4.1.7 on 2023-03-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_programa_subprograma_subprograma_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='subprograma',
            name='codigoProgramas',
        ),
    ]
