# Generated by Django 4.1.7 on 2023-10-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
