# Generated by Django 4.1.7 on 2023-10-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_programacion_ano'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosHilos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
