# Generated by Django 4.1.7 on 2023-10-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_usuarioshilo_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='publicidad',
            options={'ordering': ['nombre']},
        ),
    ]
