# Generated by Django 4.1.7 on 2023-10-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_artista_options_alter_publicidad_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='ano',
        ),
    ]
